Controller e repository quantidade de campanhas ativas
ifpebj-ti/Modulo_Marketing-CRM pull request #20
Opened 2023-10-16 00:33 UTC by deisecristiane

2023-10-16 21:32 UTC, rafxrad approved these changes

2023-10-16 23:53 UTC, EvertonLucasGomes requested changes
Tira a connection string deise

2023-10-16 23:57 UTC, rafxrad approved these changes

2023-10-17 00:08 UTC, EvertonLucasGomes approved these changes

2023-10-17 00:08 UTC, merged